### ISSUE TITLE
Submit button stroke around box

### ISSUE THREAD

**Issue by BeccsOmata** [JoshCarter8400/quarantine-movie-nights#28]
There seems to be a white line/stroke around the submit button after being pressed.

**Comment by csouthwick** [comment]
Default styling issue that happens in Chrome but not Firefox (or at least my local install of Firefox). Fix is going to be using an `<img>` tag instead of an `<input>` tag for the popcorn button. As long as the `id="search-btn" class="popcorn"` is still there, it should work fine with the existing event handler and CSS styles.
