### ISSUE TITLE
Weird Movie Card Returns

### ISSUE THREAD

**Issue by BeccsOmata** [JoshCarter8400/quarantine-movie-nights#30]
When you run a search, sometimes a few "undefined' cards come back - example "Horror" + "King" - returned two undefined cards.

**Comment by csouthwick** [comment]
This is likely due to a movie that is in TMDb but not in OMDb - so we get a movie when we do the initial search in TMDb but when we hand it off to OMDb to get the title and summary it doesn't find a match. We'll want to check if OMDb has a result in the getMovieInfo() function then only send to displayMovie() if there is a result, else don't do anything.
